
baseURL = "https://survivalcartola.github.io/"
languageCode = "pt-br"
title = "Cartola Survival"
theme = "ananke"
[pagination]
  pagerSize = 10
defaultContentLanguage = "pt-br"

[params]
  customCSS = ["css/tecnoruina.css"]
  author = "Miguel"
  description = "Sobre o Ser, a Verdade e a Ordem."
  show_reading_time = true
  mainSections = ["tractatus"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]

  [[menu.main]]
    identifier = "home"
    name = "Initium"
    url = "/"
    weight = 1

 [[menu.main]]
    identifier = "glossarium"
    name = "Glossarium"
    url = "/glossarium/"
    weight = 2

  [[menu.main]]
    identifier = "tractatus"
    name = "Tractatus"
    url = "/tractatus/"
    weight = 3

  [[menu.main]]
    identifier = "about"
    name = "Methodo"
    url = "/about/"
    weight = 4
